apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BaremetalCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: cpaas-system
  labels:
    cpaas.io/cluster-name: ${CLUSTER_NAME}
spec:
  controlPlaneLoadBalancer:
    type: ${LB_MODE}
    host: ${CONTROL_PLANE_ENDPOINT_HOST}
    port: ${CONTROL_PLANE_ENDPOINT_PORT}
${INTERNAL_LB_FIELDS}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BaremetalMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane-machine-template
  namespace: cpaas-system
  labels:
    cpaas.io/cluster-name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      machineInventoryPoolRef:
        name: ${CLUSTER_NAME}-control-plane-pool
      allocationPolicy: Ordered
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: cpaas-system
  labels:
    cpaas.io/cluster-name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: [${PODS_CIDR}]
    services:
      cidrBlocks: [${SERVICES_CIDR}]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: BaremetalCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}-control-plane
